---
# Ansible Playbook to change hostname

- name: change hostname
  hosts: routers

  tasks:
    - name: Configure Uplink
      ios_config:
        lines:
          - hostname {{hostname}}
          
