---
# Ansible Playbook to upgrade Cisco IOS

- name: Upgrade CISCO IOS
  hosts: routers
  connection: network_cli

  tasks:
    - name: Configure Uplink
      ios_config:
        parents: "Interface GigabitEthernet 2"
        lines:
          - description Ansible Test Interface
          - ip address {{ interface_ip }} 255.255.255.0
          
