---
# Ansible Playbook to config interface ip

- name: config interface ip
  hosts: routers
  connection: network_cli

  tasks:
    - name: Configure Uplink port
      ios_config:
        parents: "Interface GigabitEthernet {{ uplink_port }}"
        lines:
          - description Ansible Test Interface
          - ip address {{ uplink_ip }} {{ uplink_mask }}
