---
# Ansible Playbook to backup ios-xe config
- name: Backup router config
  hosts: routers

## Create backup folder for today
- hosts: localhost
  tasks:
   - name: Get ansible date/time facts
     setup:
       filter: "ansible_date_time"
       gather_subset: "!all"

   - name: Store DTG as fact
     set_fact:
       DTG: "{{ ansible_date_time.date }}"

   - name: Create Directory {{ hostvars.localhost.DTG }}
     file:
      path: ~/ansible/playbooks/backups/{{ hostvars.localhost.DTG }}
      state: directory
  run_once: true

## Backup Running Config
- hosts: routers
  tasks:
   - name: Backup Running Config
     ios_command:
       commands: show run
     register: config

   - name: Save output
     copy:
       content: "{{config.stdout[0]}}"
       dest: "~/ansible/playbooks/backups/{{hostvars.localhost.DTG}}/{{ inventory_hostname }}-{{hostvars.loca
lhost.DTG}}-config.txt"


## SAVE the Running Config
   - name: Save running config
     ios_config:
       save_when: always

