---
# Ansible Playbook to config ios-xe routers

- name: Config ios-xe routers
  hosts: routers

  tasks:
    - name: Configure service
      ios_config:
        lines:
          - service password-encryption


    - name: Configure SNMPv3
      ios_config:
        lines:
          - snmp-server group SNMPv3 v3 priv
        after:
          - snmp-server user snmpv3 SNMPv3 v3 auth sha AuthPwd123 priv aes 128 PrivPwd123


    - name: ACL - ACL-IN on uplink port
      ios_config:
        parents: ["ip access-list extended ACL-IN"]
        commands:
         - 10 permit tcp any any eq 22
         - 20 permit tcp any any eq www
         - 30 permit udp any any eq snmp
        match: exact
        replace: block
        before:
          - interface GigabitEthernet {{ uplink_port }}
          - no ip access-group ACL-IN in
          - no ip access-list extended ACL-IN
        after:
          - interface GigabitEthernet {{ uplink_port }}
          - ip access-group ACL-IN in


    - name: Configure Uplink port
      ios_config:
        parents: "Interface GigabitEthernet {{ uplink_port }}"
        lines:
          - description Ansible Test Interface
          - ip address {{ uplink_ip }} {{ uplink_mask }}
