---
ansible_connection: network_cli
ansible_network_os: ios
ansible_become: yes
ansible_become_method: enable
ansible_user: change_username
ansible_password: change_password
ansible_become_password: change_enable_password
